// Date: 04/08/2016 13:49:37
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelSeaUrchin extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Spike;
    ModelRenderer Side1;
    ModelRenderer Side2;
    ModelRenderer Side3;
    ModelRenderer Side4;
    ModelRenderer Spike2;
    ModelRenderer Spike3;
    ModelRenderer Spike4;
    ModelRenderer Shape1;
    ModelRenderer Spike;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Spike;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Spike;
    ModelRenderer Spike;
    ModelRenderer Spike;
    ModelRenderer Spike;
    ModelRenderer Spike;
    ModelRenderer Spike;
    ModelRenderer Spike;
    ModelRenderer Spike;
    ModelRenderer Spike;
    ModelRenderer Spike;
    ModelRenderer Spike;
    ModelRenderer Spike;
    ModelRenderer Spike;
    ModelRenderer Spike;
  
  public ModelSeaUrchin()
  {
    textureWidth = 32;
    textureHeight = 32;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(-2.5F, 19F, -2.5F, 5, 5, 5);
      Body.setRotationPoint(0F, 0F, 0F);
      Body.setTextureSize(32, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Spike = new ModelRenderer(this, 0, 11);
      Spike.addBox(2.5F, 1.5F, -0.5F, 5, 1, 1);
      Spike.setRotationPoint(0F, 22F, 0F);
      Spike.setTextureSize(32, 32);
      Spike.mirror = true;
      setRotation(Spike, 0F, 0F, -0.8726646F);
      Side1 = new ModelRenderer(this, 4, 5);
      Side1.addBox(-2.5F, 20F, -3.5F, 5, 4, 1);
      Side1.setRotationPoint(0F, 0F, 0F);
      Side1.setTextureSize(32, 32);
      Side1.mirror = true;
      setRotation(Side1, 0F, 0F, 0F);
      Side2 = new ModelRenderer(this, 3, 5);
      Side2.addBox(-2.5F, 20F, 2.5F, 5, 4, 1);
      Side2.setRotationPoint(0F, 0F, 0F);
      Side2.setTextureSize(32, 32);
      Side2.mirror = true;
      setRotation(Side2, 0F, 0F, 0F);
      Side3 = new ModelRenderer(this, 3, 5);
      Side3.addBox(-2.5F, 20F, 2.5F, 5, 4, 1);
      Side3.setRotationPoint(0F, 0F, 0F);
      Side3.setTextureSize(32, 32);
      Side3.mirror = true;
      setRotation(Side3, 0F, 1.570796F, 0F);
      Side4 = new ModelRenderer(this, 3, 5);
      Side4.addBox(-2.5F, 20F, -3.5F, 5, 4, 1);
      Side4.setRotationPoint(0F, 0F, 0F);
      Side4.setTextureSize(32, 32);
      Side4.mirror = true;
      setRotation(Side4, 0F, 1.570796F, 0F);
      Spike2 = new ModelRenderer(this, 0, 11);
      Spike2.addBox(1.5F, 2F, -1.3F, 5, 1, 1);
      Spike2.setRotationPoint(0F, 22F, 0F);
      Spike2.setTextureSize(32, 32);
      Spike2.mirror = true;
      setRotation(Spike2, 0F, 0.1745329F, -0.6283185F);
      Spike3 = new ModelRenderer(this, 0, 11);
      Spike3.addBox(1.5F, 2F, 0.3F, 5, 1, 1);
      Spike3.setRotationPoint(0F, 22F, 0F);
      Spike3.setTextureSize(32, 32);
      Spike3.mirror = true;
      setRotation(Spike3, 0F, -0.1745329F, -0.6283185F);
      Spike4 = new ModelRenderer(this, 0, 11);
      Spike4.addBox(1.5F, 2F, -1.3F, 5, 1, 1);
      Spike4.setRotationPoint(0F, 22F, 0F);
      Spike4.setTextureSize(32, 32);
      Spike4.mirror = true;
      setRotation(Spike4, 0F, 1.745329F, -0.6283185F);
      Shape1 = new ModelRenderer(this, 0, 11);
      Shape1.addBox(1.5F, 2F, 0.3F, 5, 1, 1);
      Shape1.setRotationPoint(0F, 22F, 0F);
      Shape1.setTextureSize(32, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 1.396263F, -0.6283185F);
      Spike = new ModelRenderer(this, 0, 11);
      Spike.addBox(2.5F, 1.5F, -0.5F, 5, 1, 1);
      Spike.setRotationPoint(0F, 22F, 0F);
      Spike.setTextureSize(32, 32);
      Spike.mirror = true;
      setRotation(Spike, 0F, 1.570796F, -0.8726646F);
      Shape1 = new ModelRenderer(this, 0, 11);
      Shape1.addBox(3F, 1F, -0.5F, 5, 1, 1);
      Shape1.setRotationPoint(0F, 22F, 0F);
      Shape1.setTextureSize(32, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0.7853982F, -0.6283185F);
      Shape1 = new ModelRenderer(this, 0, 11);
      Shape1.addBox(3F, 1F, -0.5F, 5, 1, 1);
      Shape1.setRotationPoint(0F, 22F, 0F);
      Shape1.setTextureSize(32, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 2.356194F, -0.6283185F);
      Shape1 = new ModelRenderer(this, 0, 11);
      Shape1.addBox(1.5F, 2F, -1.3F, 5, 1, 1);
      Shape1.setRotationPoint(0F, 22F, 0F);
      Shape1.setTextureSize(32, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, -2.96706F, -0.6283185F);
      Shape1 = new ModelRenderer(this, 0, 11);
      Shape1.addBox(1.5F, 2F, 0.5F, 5, 1, 1);
      Shape1.setRotationPoint(0F, 22F, 0F);
      Shape1.setTextureSize(32, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 2.96706F, -0.6283185F);
      Spike = new ModelRenderer(this, 0, 11);
      Spike.addBox(2.5F, 1.5F, -0.5F, 5, 1, 1);
      Spike.setRotationPoint(0F, 22F, 0F);
      Spike.setTextureSize(32, 32);
      Spike.mirror = true;
      setRotation(Spike, 0F, 3.141593F, -0.8726646F);
      Shape1 = new ModelRenderer(this, 0, 11);
      Shape1.addBox(3F, 1F, -0.5F, 5, 1, 1);
      Shape1.setRotationPoint(0F, 22F, 0F);
      Shape1.setTextureSize(32, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, -2.356194F, -0.6283185F);
      Shape1 = new ModelRenderer(this, 0, 11);
      Shape1.addBox(3F, 1F, -0.5F, 5, 1, 1);
      Shape1.setRotationPoint(0F, 22F, 0F);
      Shape1.setTextureSize(32, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, -0.7853982F, -0.6283185F);
      Shape1 = new ModelRenderer(this, 0, 11);
      Shape1.addBox(1.5F, 2F, -1.3F, 5, 1, 1);
      Shape1.setRotationPoint(0F, 22F, 0F);
      Shape1.setTextureSize(32, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, -1.396263F, -0.6283185F);
      Shape1 = new ModelRenderer(this, 0, 11);
      Shape1.addBox(1.5F, 2F, 0.3F, 5, 1, 1);
      Shape1.setRotationPoint(0F, 22F, 0F);
      Shape1.setTextureSize(32, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, -1.745329F, -0.6283185F);
      Spike = new ModelRenderer(this, 0, 11);
      Spike.addBox(2.5F, 1.5F, -0.5F, 5, 1, 1);
      Spike.setRotationPoint(0F, 22F, 0F);
      Spike.setTextureSize(32, 32);
      Spike.mirror = true;
      setRotation(Spike, 0F, -1.570796F, -0.8726646F);
      Spike = new ModelRenderer(this, 0, 11);
      Spike.addBox(2.5F, 0F, -1.5F, 5, 1, 1);
      Spike.setRotationPoint(0F, 22F, 0F);
      Spike.setTextureSize(32, 32);
      Spike.mirror = true;
      setRotation(Spike, 0F, 0.2617994F, -0.7853982F);
      Spike = new ModelRenderer(this, 0, 11);
      Spike.addBox(2.5F, 0F, 0.5F, 5, 1, 1);
      Spike.setRotationPoint(0F, 22F, 0F);
      Spike.setTextureSize(32, 32);
      Spike.mirror = true;
      setRotation(Spike, 0F, -0.2617994F, -0.7853982F);
      Spike = new ModelRenderer(this, 0, 11);
      Spike.addBox(2.5F, 0F, 0.5F, 5, 1, 1);
      Spike.setRotationPoint(0F, 22F, 0F);
      Spike.setTextureSize(32, 32);
      Spike.mirror = true;
      setRotation(Spike, 0F, 1.308997F, -0.7853982F);
      Spike = new ModelRenderer(this, 0, 11);
      Spike.addBox(2.5F, 0F, -1.5F, 5, 1, 1);
      Spike.setRotationPoint(0F, 22F, 0F);
      Spike.setTextureSize(32, 32);
      Spike.mirror = true;
      setRotation(Spike, 0F, 1.832596F, -0.7853982F);
      Spike = new ModelRenderer(this, 0, 11);
      Spike.addBox(2.5F, 0F, 0.5F, 5, 1, 1);
      Spike.setRotationPoint(0F, 22F, 0F);
      Spike.setTextureSize(32, 32);
      Spike.mirror = true;
      setRotation(Spike, 0F, 2.879793F, -0.7853982F);
      Spike = new ModelRenderer(this, 0, 11);
      Spike.addBox(2.5F, 0F, -1.5F, 5, 1, 1);
      Spike.setRotationPoint(0F, 22F, 0F);
      Spike.setTextureSize(32, 32);
      Spike.mirror = true;
      setRotation(Spike, 0F, -2.879793F, -0.7853982F);
      Spike = new ModelRenderer(this, 0, 11);
      Spike.addBox(2.5F, 0F, -1.5F, 5, 1, 1);
      Spike.setRotationPoint(0F, 22F, 0F);
      Spike.setTextureSize(32, 32);
      Spike.mirror = true;
      setRotation(Spike, 0F, -1.308997F, -0.7853982F);
      Spike = new ModelRenderer(this, 0, 11);
      Spike.addBox(2.5F, 0F, 0.5F, 5, 1, 1);
      Spike.setRotationPoint(0F, 22F, 0F);
      Spike.setTextureSize(32, 32);
      Spike.mirror = true;
      setRotation(Spike, 0F, -1.832596F, -0.7853982F);
      Spike = new ModelRenderer(this, 0, 11);
      Spike.addBox(2.5F, 0F, -0.5F, 5, 1, 1);
      Spike.setRotationPoint(0F, 22F, 0F);
      Spike.setTextureSize(32, 32);
      Spike.mirror = true;
      setRotation(Spike, 0F, 0F, -1.22173F);
      Spike = new ModelRenderer(this, 0, 11);
      Spike.addBox(2.5F, 0F, -0.5F, 5, 1, 1);
      Spike.setRotationPoint(0F, 22F, 0F);
      Spike.setTextureSize(32, 32);
      Spike.mirror = true;
      setRotation(Spike, 0F, 1.570796F, -1.22173F);
      Spike = new ModelRenderer(this, 0, 11);
      Spike.addBox(2.5F, 0F, -0.5F, 5, 1, 1);
      Spike.setRotationPoint(0F, 22F, 0F);
      Spike.setTextureSize(32, 32);
      Spike.mirror = true;
      setRotation(Spike, 0F, 3.141593F, -1.22173F);
      Spike = new ModelRenderer(this, 0, 11);
      Spike.addBox(2.5F, 0F, -0.5F, 5, 1, 1);
      Spike.setRotationPoint(0F, 22F, 0F);
      Spike.setTextureSize(32, 32);
      Spike.mirror = true;
      setRotation(Spike, 0F, -1.570796F, -1.22173F);
      Spike = new ModelRenderer(this, 0, 11);
      Spike.addBox(3F, -0.5F, -0.52F, 5, 1, 1);
      Spike.setRotationPoint(0F, 22F, 0F);
      Spike.setTextureSize(32, 32);
      Spike.mirror = true;
      setRotation(Spike, 0F, -1.570796F, -1.570796F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Body.render(f5);
    Spike.render(f5);
    Side1.render(f5);
    Side2.render(f5);
    Side3.render(f5);
    Side4.render(f5);
    Spike2.render(f5);
    Spike3.render(f5);
    Spike4.render(f5);
    Shape1.render(f5);
    Spike.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Spike.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Spike.render(f5);
    Spike.render(f5);
    Spike.render(f5);
    Spike.render(f5);
    Spike.render(f5);
    Spike.render(f5);
    Spike.render(f5);
    Spike.render(f5);
    Spike.render(f5);
    Spike.render(f5);
    Spike.render(f5);
    Spike.render(f5);
    Spike.render(f5);
    Spike.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
